### ISSUE TITLE
Start NodeRed with memory parameter

### ISSUE THREAD

**Issue by soloam** [tprelog/iocage-node-red#2]
Hello, is it possible to modify the service call to allays call with --max-old-space-size=16000? My flows are very complex and I need this instruction to them start nodered (https://nodered.org/docs/getting-started/raspberrypi), normaly its used in the raspPi, but I need it in my flows to avoid crashes. This problem is reported in te nodered github and being analysed at the moment by the devs.

Thank you

**Comment by tprelog** [comment]
I'll work on adding something for this in the 11.3-RELEASE.

 For now you can just manually edit the startup file `/usr/local/etc/rc.d/nodered`

Around line 47 you should find
``` 
  rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} /usr/local/bin/node-red -u ${nodered_dir} ${rc_flags}"
```
After looking at your link and assuming size=16000, I think this should do the trick
``` 
  rc_flags="-f -o ${logfile} -P ${pidfile} -p ${pidfile_child} /usr/local/bin/node-red-pi --max-old-space-size=16000 -u ${nodered_dir} ${rc_flags}"
```

 Sorry it's been so long again if you're still have trouble.

**Comment by tprelog** [comment]
I've updated the service script. Please give this a try

**Update the nodered service script**
```bash
iocage console node-red
pkg install -y wget ca_root_nss
wget -O /usr/local/etc/rc.d/nodered https://raw.githubusercontent.com/tprelog/iocage-node-red/11.3-RELEASE/overlay/usr/local/etc/rc.d/nodered
chmod +x /usr/local/etc/rc.d/nodered
```
**Use `nodered_moss` to set and enable `max-old-space-size`**.
- for example to use `max-old-space-size=512`
```bash
sysrc nodered_moss=512
```

**Restart Node-RED**
```bash
service nodered restart
```

**If you wish to disable  `max-old-space-size` after it has been set**
```bash
sysrc -x nodered_moss
```
