### ISSUE TITLE
upgrading node red?

### ISSUE THREAD

**Issue by hros** [tprelog/iocage-node-red#8]
how do I upgrade the node red version in this plugin?
similar plugins (home assistant, esphome) have a console menu for upgrading. what's the procedure in this plugin?

**Comment by Ekristoffe** [comment]
upgrading the plugin require:
Go to "Jail", 
select Node-RED jail (click on the arrow on the right side),
click on "Shell",
type "service nodered upgrade"  press enter.
Enjoy

**Comment by hros** [comment]
thanks
works perfectly
I would suggest updating the login screen of the jail, which currently reads:
```
| \ || . || . \| __>| . \| __>| . \
|   || | || | || _> |   /| _> | | |
|_\_|`___'|___/|___>|_\_\|___>|___/
                                   

- Plugin directory for Node-RED
    /var/db/nodered

- Plugin default Node-RED settings
    /var/db/nodered/settings.js

- Logfile for Node-RED daemon
    /var/log/nodered_daemon.log

- Control the node-red daemon
    service nodered [start|stop|status|restart]
```

by changing the last line to:
```
    service nodered [start|stop|status|restart|upgrade]

```

**Comment by Ekristoffe** [comment]
true true ...
